# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC1verify():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC1verify(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.ID, "login_credentials").click()
    self.driver.find_element(By.ID, "login_credentials").click()
    element = self.driver.find_element(By.ID, "login_credentials")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    assert self.driver.title == "Swag Labs"
    self.driver.find_element(By.ID, "login_credentials").click()
    self.driver.find_element(By.ID, "login_credentials").click()
    element = self.driver.find_element(By.ID, "login_credentials")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, ".login_password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login_password").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".login_password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauceabc")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"error\"]").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"error\"]").text == "Epic sadface: Username and password do not match any user in this service"
    self.driver.close()
    assert self.driver.title == "Swag Labs"
    self.driver.find_element(By.ID, "login_credentials").click()
    self.driver.find_element(By.ID, "login_credentials").click()
    element = self.driver.find_element(By.ID, "login_credentials")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    self.driver.find_element(By.CSS_SELECTOR, ".login_password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login_password").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".login_password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".app_logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".app_logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".app_logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".app_logo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".app_logo").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".app_logo").text == "Swag Labs"
    self.driver.close()
  
